config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :rides, only: [:index, :new, :create]
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  street     :string           not null
#  city       :string           not null
#  country    :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  ride_id    :integer
#

class Address < ActiveRecord::Base
  belongs_to :ride, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/distance.rb
require 'addressable/uri'
require 'httparty'
class Distance
  def initialize(address1, address2)
    @start_address = address1
    @destination_address = address2
  end

  def get_distance
    distance = 0
    if @start_address.blank? || @destination_address.blank?
     	return nil
    else
      s_address = URI.encode(@start_address.street+', '+@start_address.city+', '+@start_address.country)
      e_address = URI.encode(@destination_address.street+', '+@destination_address.city+', '+@destination_address.country)

      base_url = 'http://maps.googleapis.com/maps/api/directions/json'
      req_url = "#{base_url}?origin=#{s_address}&destination=#{e_address}&sensor=false"
      request = HTTParty.get(req_url)
      # raise 'Dupa'
      if request['routes'].empty?
  	     return nil
      else
        begin
          distance = request['routes'][0]['legs'][0]['distance']['text']
        rescue NoMethodError
          puts request.inspect
          exit
        end
      return distance
      end
   end
  end
end

app/models/provider.rb
# == Schema Information
#
# Table name: providers
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Provider < ActiveRecord::Base
  validates :name, presence: true
end

app/models/ride.rb
# == Schema Information
#
# Table name: rides
#
#  id          :integer          not null, primary key
#  price       :float            not null
#  distance    :float            not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  provider_id :integer
#

class Ride < ActiveRecord::Base
  # **VALIDATIONS***********#
  validates_presence_of :price, :distance, :user_id, :provider_id
  before_validation :set_distance
  # ************************#

  # **ASSOCIATIONS**********#
  belongs_to :user
  belongs_to :provider
  has_one :start_address, class_name: "Address", dependent: :destroy
  has_one :destination_address, class_name: "Address", dependent: :destroy
  # ************************#
  accepts_nested_attributes_for :start_address, :destination_address
  # **METHODS**********#
  private
  def set_distance
    @distance = Distance.new(self.start_address, self.destination_address)
    unless @distance.nil?
      self.distance = @distance.get_distance
    else
      errors.add(:base, "issue with counting distance between addresses")
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rides, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      sanitized_params = %i(
        email
        password
        password_confirmation
      )
      u.permit(sanitized_params)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_providers, only: [:new, :create]
  expose :rides, -> { current_user.rides.all }
  expose :ride, attributes: :ride_params
  def index
    @week_rides = rides.where("created_at > ?", Date.today.at_beginning_of_week)
                       .group_by{ |n| l(n.created_at, format: :default)}
    @month_rides = rides.where("created_at > ?", Date.today.at_beginning_of_month)
                        .group_by{ |n| l(n.created_at, format: :default)}
  end

  def new
    @start_address = ride.build_start_address
    @destination_address = ride.build_destination_address
  end

  def create
    ride.user = current_user
    ride.assign_attributes(ride_params)
    if ride.save
      redirect_to rides_path, notice: I18n.t('shared.created', resource: 'Ride')
    else
      render :new
    end
  end

  private
  def ride_params
    params.require(:ride).permit(:price, :provider_id,
        start_address_attributes: [:street, :city, :country],
        destination_address_attributes: [:street, :city, :country])
  end

  def set_providers
    @providers = Provider.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(*paths)
  'active' if paths.any?{ |path| current_page?(path) }
  end
end

app/helpers/rides_helper.rb
module RidesHelper
  # map names of all providers
  def provider_collection
    Provider.all.map{|p| [p.name, p.id]}
  end

  # sum km of rides
  def sum_rides(rides)
    return km(0) if rides.count == 0
    sum = rides.map(&:distance).sum.to_f
    return km(sum.nice)
  end

  # average sum of km per rides count
  def avg_rides(rides)
    return km(0) if rides.count == 0
    avg = (rides.map(&:distance).sum / rides.count).to_f
    return km(avg.nice)
  end

  # average price paid for rides
  def avg_price(rides)
    return euro(0) if rides.count == 0
    avg = (rides.map(&:price).sum / rides.count).to_f
    return euro(avg.nice)
  end

  # display providers
  def display_providers
    rides.map{|ride| ride.provider.name}.uniq.join(', ')
  end

  # e.g. 12.45 km instead 12.45
  def km(dist)
    "#{dist}km"
  end

  # e.g. 45.22 EUR instead 45.22
  def euro(price)
    "#{price} EUR"
  end
end

app/views/home/_form.html.slim
= simple_form_for @ride, html:{ class: 'form-horizontal'} do |f|
  .row
    .col-md-5
      = f.simple_fields_for :start_address do |sa|
        = sa.input :street
        = sa.input :city
        = sa.input :country, prompt: "Select country"
    .col-md-5.col-md-offset-2
      = f.simple_fields_for :destination_address do |da|
        = da.input :street
        = da.input :city
        = da.input :country, prompt: "Select country"
  = f.input :price
  = f.input :provider_id, collection: @providers.map{|p| [p.name, p.id]},
                          prompt: "Select provider"
  = f.button :submit, class: "btn btn-primary btn-block"

app/views/home/index.html.slim
h2 Riderank
p Log in or register account to add own rides and see history of travels.

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="true" data-target="#navbar" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to ENV['APP_NAME'], root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li class=(active?(rides_path))
          = link_to t('navbar.rides'), rides_path        
      ul.nav.navbar-nav.navbar-right
        - unless user_signed_in?
          li class=(active?(new_user_registration_path))
            = link_to t('navbar.register'), new_user_registration_path 
          li class=(active?(new_user_session_path))
            = link_to t('navbar.login'), new_user_session_path
        - else
          li
            = link_to t('navbar.logout'), destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title= content_for?(:title) ? yield(:title) : ENV['APP_NAME']
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      = render 'layouts/navigation'
    main role="main"
      .container
        = render 'shared/messages'
        = yield

app/views/rides/_form.html.slim
= simple_form_for ride, html:{ class: 'form-horizontal'} do |f|
  = f.error_notification
  .row
    .col-md-5
      = f.simple_fields_for :start_address do |sa|
        = sa.input :street, required: true
        = sa.input :city, required: true
        = sa.input :country, required: true, prompt: "Select country"
    .col-md-5.col-md-offset-2
      = f.simple_fields_for :destination_address do |da|
        = da.input :street, required: true
        = da.input :city, required: true
        = da.input :country, required: true, prompt: "Select country"
  = f.input :price
  = f.input :provider_id, collection: provider_collection,
                          prompt: "Select provider", include_blank: false
  = link_to t('shared.back'), rides_path, class: 'btn btn-default'
  = f.button :submit, class: 'btn btn-primary'

app/views/rides/index.html.slim
= link_to t('shared.add_new_item'), new_ride_path, class: 'btn btn-primary'
h4 Current week
table.table.table-inverse
  thead
    tr
      th= t('ride.columns.day')
      th= t('ride.columns.rides_sum')
      th= t('ride.columns.avg_ride')
      th= t('ride.columns.avg_price')
      th= t('ride.columns.taxis')
  tbody
    - unless @week_rides.blank?
      - @week_rides.each do |created_at, rides|
        tr
          td
            = created_at
          td
            = sum_rides(rides)
          td
            = avg_rides(rides)
          td
            = avg_price(rides)
          td
            = display_providers
    - else
      tr
        td.well colspan="5"
          .text-center
            | Empty

hr
h4 Current Month
table.table.table-inverse
  thead
    tr
      th= t('ride.columns.day')
      th= t('ride.columns.rides_sum')
      th= t('ride.columns.avg_ride')
      th= t('ride.columns.avg_price')
      th= t('ride.columns.taxis')
  tbody
    - unless @month_rides.blank?
      - @month_rides.each do |created_at, rides|
        tr
          td
            = created_at
          td
            = sum_rides(rides)
          td
            = avg_rides(rides)
          td
            = avg_price(rides)
          td
            = display_providers
    - else
      tr
        td.well colspan="5"
          .text-center
            | Empty

app/views/rides/new.html.slim
h2 Register ride
= render 'form'

app/views/shared/_messages.html.slim
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name == :notice ? "success" : "error"}") 
      a.close data-dismiss="alert"  ×
      = content_tag :div, msg, :id => "flash_#{name}"